import { prisma } from "@/lib/prisma";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
import { enUS } from "date-fns/locale";

export const dynamic = "force-dynamic";

export default async function HistoryPage() {
  const analyses = await prisma.analysis.findMany({
    orderBy: { createdAt: 'desc' }
  });

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Analysis History</h2>
        <p className="text-muted-foreground mt-2">
          Browse all analyses generated by AI.
        </p>
      </div>

      <Card className="bg-card border-border shadow-sm">
        <CardHeader>
          <CardTitle>Recent Analyses</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border border-border">
            <Table>
              <TableHeader className="bg-muted/50">
                <TableRow className="border-border hover:bg-transparent">
                  <TableHead className="text-muted-foreground">Account</TableHead>
                  <TableHead className="text-muted-foreground">Date</TableHead>
                  <TableHead className="text-muted-foreground">Global Sentiment</TableHead>
                  <TableHead className="text-muted-foreground">Frustrations</TableHead>
                  <TableHead className="text-muted-foreground">Opportunities</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {analyses.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="h-24 text-center text-muted-foreground">
                      No analyses found.
                    </TableCell>
                  </TableRow>
                ) : (
                  analyses.map((analysis) => (
                    <TableRow key={analysis.id} className="border-border hover:bg-muted/50">
                      <TableCell className="font-medium">@{analysis.instagramUsername}</TableCell>
                      <TableCell>{format(new Date(analysis.createdAt), 'MMM dd yyyy, HH:mm', { locale: enUS })}</TableCell>
                      <TableCell>
                        <Badge 
                          variant="outline" 
                          className={
                            analysis.sentimentGlobal.toLowerCase().includes('positif') ? "text-emerald-500 border-emerald-500/20 bg-emerald-500/10" :
                            analysis.sentimentGlobal.toLowerCase().includes('négatif') || analysis.sentimentGlobal.toLowerCase().includes('negatif') ? "text-rose-500 border-rose-500/20 bg-rose-500/10" :
                            "text-amber-500 border-amber-500/20 bg-amber-500/10"
                          }
                        >
                          {analysis.sentimentGlobal}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground">
                          {((analysis.frustrations as string[]) || []).length} items
                        </span>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground">
                          {((analysis.opportunitesBusiness as string[]) || []).length} items
                        </span>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
